### ISSUE TITLE
Hide tabs in the Ediff Control Panel buffer?

### ISSUE THREAD

**Issue by duianto** [ema2159/centaur-tabs#126]
Should the `*Ediff Control Panel*` buffer be excluded from showing tabs by default?

#### With just Emacs and `centaur-tabs`
- `M-x ediff`
- choose the first file
- choose the second file

The `*Ediff Control Panel*` buffer opens in a separate frame.

The tabs are not visible by default when the help frame is "folded":

![emacs_2020-09-29_14-05-06](https://user-images.githubusercontent.com/13420573/94556051-cb8a0900-025c-11eb-8f6b-dcb819d7becc.png)

But after pressing `?`, then the tabs appear.

![emacs_2020-09-29_14-05-34](https://user-images.githubusercontent.com/13420573/94556174-f4aa9980-025c-11eb-8376-cb7a0bf9e4dd.png)

#### In Spacemacs
Currently there's a `tabs` layer, that uses this package.

But there's a WIP branch, to enable `centaur-tabs` with a `dotspacemacs-buffer-tabs` variable.
https://github.com/syl20bnr/spacemacs/commits/buffertabs

Spacemacs doesn't show the Ediff Control Panel buffer in a separate Emacs frame, 
the buffer is shown at the bottom of the current Emacs frame.

The tabs are visible when the buffer is folded, 
which pushes down the text "Type ? for help", below the mode line.

![emacs_2020-09-29_14-35-03](https://user-images.githubusercontent.com/13420573/94559743-f591fa00-0261-11eb-96a7-1d45b3ff8443.png)

The tabs are also visible when the Ediff help is visible:

![emacs_2020-09-29_14-35-12](https://user-images.githubusercontent.com/13420573/94559936-3e49b300-0262-11eb-9b61-639a93a9ff06.png)

It might not make sense to switch tabs while ediffing, 
therefore it might be best to hide the tabs by default,
in the `*Ediff Control Panel*` buffer.

#### System info
centaur-tabs-20200821.335/
GNU Emacs 27.1 (build 1, x86_64-w64-mingw32) of 2020-08-21
Windows 10 2004

**Comment by countvajhula** [comment]
I'd broaden the scope of this issue to include any buffers that "don't need to show tabs." Maybe centaur tabs already does this to some extent, since I don't usually see tabs in popup windows. But another case I noticed today:
- When quitting emacs it sometimes shows a buffer in the minibuffer area containing a list of running processes. "Active processes exist. Exit anyway?" With Centaur tabs enabled, the actual processes are not visible because I think Emacs sizes the buffer without accounting for the additional height of the tabs.

**Comment by ema2159** [comment]
Done. I just modified the `centaur-tabs-excluded-prefixes` list. I think though that the list is getting too big to I'll try to look for a better way to exclude buffers, probably by using pattern matching.

**Comment by ml653** [comment]
I'm still seeing this issue when opening minibuffer in terminal mode when centaur-tabs-mode is on.  The solution for me was to turn off centaur tabs when I'm in a mini-buffer
