### ISSUE TITLE
Centaur Tabs causing high CPU on macOS

### ISSUE THREAD

**Issue by mexisme** [ema2159/centaur-tabs#88]
Using Spacemacs on macOS, I get very high CPU usage when Centaur Tabs is enabled:
- 75-90% CPU usage (as shown by `htop`) when running with a GUI
- CPU usage drops to ~20% in a Terminal.
- CPU appears to increase when running org-mode.
- Tried disabling a few features, like 
- Profiling shows that 55% of Emacs' CPU is due to the `redisplay_internal` function, which seems to be largely due `spaceline-ml-main`.

I've tried simplifying Spacemacs' theme options, disabling several packages, and it doesn't seem to help much.

By chance, one time I noticed a function with the name "centaur" in it was using a lot of CPU, so I disabled the package, and CPU dropped to below 1% (on average).

I'm not sure how to diagnose this from Emacs, beyond minimal things like running the profiler, and even then I'm not sure what to look at, there.

**Comment by tnira** [comment]
I face this problem in same environment.
Reverting to [0383af0](https://github.com/ema2159/centaur-tabs/commit/0383af01742de0a33e5eab3d8fbcd0829db6c2f0) eliminates this problem.

**Comment by ema2159** [comment]
That's pretty odd, in fact I've been doing some performance optimizations in order to avoid constant unnecessary recalculations. I would need something more specific like a trace given that I don't have access to any macOS devices.

**Comment by ema2159** [comment]
@tnira that's really really odd because the commits after 0383af0 just do two things:
- The first one adds an idle timer that stops the tabs from recalculating every time the user types or moves the cursor and only recalculates them once after 0.3s of idle time.
-The second one removes the hook to the buffer-list-update hook which was unnecessary and just was recalculating the tabs each time company created a *temp buffer.
I would like to see if this persists on a non macOS environment, so if any of you have access to another system please check if the problem persists.

**Comment by tnira** [comment]
I did a clean install of ubuntu18 and installed only centaur-tabs with default settings for spacemacs.
CPU usage increases significantly compared to when centaur-tabs is not installed.

**Comment by ema2159** [comment]
That's pretty interesting. Spacemacs tends to misbehave from time to time. As far as I know this doesn't happen in Doom. It probably has to do with the timer I added and something inside Spacemacs having conflicts with it. Some information about what function is consuming the time or something like a trace would be really helpful.

**Comment by tnira** [comment]
I'm using Emacs's profiler feature to look for problems in Spacemacs.

The following results were obtained with `M-x profiler-report.`
![スクリーンショット 2020-02-27 12 39 04](https://user-images.githubusercontent.com/3020006/75411359-53740180-5962-11ea-9e9d-8a2d4f8e238b.png)

In addition, the following results were obtained with `M-x elp-instrument-list <RET> cenataur-tabs <RET>`.
![スクリーンショット 2020-02-27 13 05 17](https://user-images.githubusercontent.com/3020006/75411372-5ec72d00-5962-11ea-830b-4b8e2529e40b.png)

Going forward, I have no idea what I can do to identify conflicting places in Spacemacs.
I understand this is a phenomenon with Spacemac, but I'd be glad to give me some advice.

**Comment by ema2159** [comment]
That Spacemacs profiler report worries me a little bit. I don't quite understand why `centaur-tabs-line` is called so many times. It shouldn't. As you see the `centaur-tabs-after-modifying-buffer` is called many times but overall the time it takes is little because it only redisplays the tabs when Emacs is idle, every other time it's basically a boolean evaluation which takes practically no time. Also, another thing that you can do to help me is to do `M-x debug-on-entry RET centaur-tabs-line`. Hopefully the trace will show us what's triggering the redisplay in Spacemacs.

**Comment by sorawee** [comment]
Just want to confirm that I have this problem too, and after disabling `centaur-tabs`, the high CPU problem goes away.

**Comment by ema2159** [comment]
With the help of the all mighty Doom Emacs owner, I think we have a potential solution to the performance and flickering problems, although I will be able to try it until Sunday because I'm on vacation and I didn't bring my laptop.

**Comment by ema2159** [comment]
Done! It should be fixed now.

**Comment by sorawee** [comment]
Hmm. It's still not fixed for me unfortunately. I made sure that my `centaur-tabs.el` has `(let (buffer-list-update-hook)` before `(with-temp-buffer` (that is, it is indeed up-to-date).

**Comment by ema2159** [comment]
@sorawee could you show me a screenshot from the profiler?

**Comment by sorawee** [comment]
Here it is:

<img width="309" alt="Screen Shot 2020-03-01 at 19 24 14" src="https://user-images.githubusercontent.com/9099577/75642966-410ff700-5bf2-11ea-9410-1246b1711e3a.png">

**Comment by sorawee** [comment]
Note that if I revert the changes in 3658efccd8e17702d1906d, the issue goes away.

**Comment by ema2159** [comment]
@sorawee are you sure that you updated the package correctly?
![image](https://user-images.githubusercontent.com/17773218/75643570-0c596b00-5c05-11ea-84b9-07d6ed952332.png)
That's my profiler report, and 3658efc shouldn't trigger any unnecessary recalculations (unless Spacemacs has some weird issues with timers, which I doubt).
@tnira @mexisme, could you do some profiling just to see if this also happens to you?

**Comment by tnira** [comment]
I immediately started using the latest version.
As far as I have tried, this fix does not lead to lower CPU utilization.
![スクリーンショット 2020-03-02 13 45 58](https://user-images.githubusercontent.com/3020006/75646491-250d6380-5c8d-11ea-8ef3-49ab45b397d8.png)

I try to isolate the problem as much as possible, but I haven't done that yet.

**Comment by sorawee** [comment]
I tried to `debug-on-entry` on `centaur-tabs-line`, but it seems to have no effect. The tutorial of `debug-on-entry` seems to suggest that we need to "invoke" it somehow, but I guess because it's already running, it's not invoked?

Another thing I'm curious is, for c3254ef87075b0d, you add `(let (buffer-list-update-hook) ...)` to the code. What does that do? I've personally never seen this form of `let` before. Thought that `let` must following by a list of bindings?

**Comment by ema2159** [comment]
@sorawee. I'm not quite sure, that's what Henrik (Doom maintainer) advised me to do. He explains some details here: https://github.com/daveduthie/doom-emacs/commit/73f29ccf1c11c260e60ca06dcdb09b37515eb909.
However, you mentioned that removing the timer (changes from 3658efc) does have a positive impact. @tnira can you confirm this?

**Comment by xml-js-dev** [comment]
I can confirm this issue on Ubuntu 18.04, using Emacs 27 on release tip (not spacemacs). Profiler shows a total of 50% CPU usage from Centaur tabs during light editing (e.g. commenting-out lines). I'm using the icons integration with centaur tabs, but otherwise it's stock. As soon as I disable centaur tabs, Emacs is smooth as butter.

**Comment by sorawee** [comment]
> Another thing I'm curious is, for c3254ef, you add (let (buffer-list-update-hook) ...) to the code. What does that do? I've personally never seen this form of let before. Thought that let must following by a list of binding pairs?

Just to answer my own question. In elisp, this form of `let` means declare `buffer-list-update-hook`, but don't assign it any value (from https://stackoverflow.com/a/32802503/718349). I fail to see how this would solve the problem, though...

**Comment by ema2159** [comment]
@sorawee now I understand. The problem was that the `(with-temp-buffer...` function although it only creates a temporal buffer, it triggers the `buffer-list-update-hook` which triggers a lot of functions and also unnecessarily redisplays the tabs indefinitely. Wrapping the `(with-temp-buffer...` with that `let` statement "empties" the `buffer-list-update-hook` inside the scope of that let statement, so when `(with-temp-buffer...` triggers the hook, it doesn't execute any functions.

**Comment by ema2159** [comment]
@sorawee @mexisme @tnira how about now?

**Comment by sorawee** [comment]
It's fixed! Thank you :)

**Comment by ema2159** [comment]
Finally! Thanks!!!!

**Comment by sorawee** [comment]
A quick note: while it's finally not taking 90% CPU usage, it's still taking about 30%. While this is totally manageable for me, it might suggest that there's a lurking bug somewhere...

**Comment by AlessandroW** [comment]
I have the same issue here:
![image](https://user-images.githubusercontent.com/29565912/101194875-e57e0880-365e-11eb-8466-fba9fbb6f044.png)
Using `(package! centaur-tabs :pin "5453317b6b9f68bfbd934eee3b883207bfa331e0")`
